name: ssml-builder
version: '0.1.0.0'
description: A DSL for building SSML documents
synopsis: A DSL for building SSML documents
category: Text
author: Maciej Bielecki
maintainer: maciej.bielecki@prati.pl
copyright: 2018 Maciej Bielecki
license: BSD3
github: restaumatic/ssml-builder
extra-source-files:
- README.md
dependencies:
- base >=4.7 && <5

library:
  source-dirs: src
  exposed-modules:
  - Text.SSML.Builder
  dependencies:
  - data-default
  - xml >=1.3 && <2

tests:
  tests:
    source-dirs: test
    main: Spec.hs
    dependencies:
    - ssml-builder
    - hspec
